-- Create the group_links table
CREATE TABLE group_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_id BIGINT NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  description TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create index on website_id for faster lookups
CREATE INDEX idx_group_links_website_id ON group_links (website_id);

-- Enable Row Level Security
ALTER TABLE group_links ENABLE ROW LEVEL SECURITY;

-- RLS policies
CREATE POLICY "Allow authenticated users to read group_links"
  ON group_links FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Allow authenticated users to insert group_links"
  ON group_links FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Allow authenticated users to update group_links"
  ON group_links FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow authenticated users to delete group_links"
  ON group_links FOR DELETE
  TO authenticated
  USING (true);

-- Auto-update updated_at on row changes
CREATE OR REPLACE FUNCTION update_group_links_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER group_links_updated_at
  BEFORE UPDATE ON group_links
  FOR EACH ROW
  EXECUTE FUNCTION update_group_links_updated_at();
