-- Create the news_card_domains table (list of domain names)
CREATE TABLE news_card_domains (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE news_card_domains ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to read news_card_domains"
  ON news_card_domains FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Allow authenticated users to insert news_card_domains"
  ON news_card_domains FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Allow authenticated users to delete news_card_domains"
  ON news_card_domains FOR DELETE
  TO authenticated
  USING (true);

-- Create the news_cards table
CREATE TABLE news_cards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL,
  title TEXT,
  description TEXT,
  image_url TEXT,
  og_title TEXT,
  og_description TEXT,
  og_image_url TEXT,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE news_cards ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to read news_cards"
  ON news_cards FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Allow authenticated users to insert news_cards"
  ON news_cards FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Allow authenticated users to update news_cards"
  ON news_cards FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow authenticated users to delete news_cards"
  ON news_cards FOR DELETE
  TO authenticated
  USING (true);

-- Function to auto-update updated_at on row changes
CREATE OR REPLACE FUNCTION update_news_cards_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER news_cards_updated_at
  BEFORE UPDATE ON news_cards
  FOR EACH ROW
  EXECUTE FUNCTION update_news_cards_updated_at();

-- Create the junction table for news_cards <-> domains
CREATE TABLE news_card_domain_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  news_card_id BIGINT NOT NULL REFERENCES news_cards(id) ON DELETE CASCADE,
  domain_id BIGINT NOT NULL REFERENCES news_card_domains(id) ON DELETE CASCADE,
  UNIQUE(news_card_id, domain_id)
);

-- Index for faster lookups
CREATE INDEX idx_news_card_domain_assignments_card ON news_card_domain_assignments (news_card_id);
CREATE INDEX idx_news_card_domain_assignments_domain ON news_card_domain_assignments (domain_id);

-- Enable Row Level Security
ALTER TABLE news_card_domain_assignments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to read news_card_domain_assignments"
  ON news_card_domain_assignments FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Allow authenticated users to insert news_card_domain_assignments"
  ON news_card_domain_assignments FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Allow authenticated users to delete news_card_domain_assignments"
  ON news_card_domain_assignments FOR DELETE
  TO authenticated
  USING (true);
