-- Create the group_event_locations table
CREATE TABLE group_event_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_id BIGINT NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  address TEXT,
  parking_info TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_group_event_locations_website_id ON group_event_locations (website_id);

ALTER TABLE group_event_locations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to read group_event_locations"
  ON group_event_locations FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Allow authenticated users to insert group_event_locations"
  ON group_event_locations FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Allow authenticated users to update group_event_locations"
  ON group_event_locations FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow authenticated users to delete group_event_locations"
  ON group_event_locations FOR DELETE
  TO authenticated
  USING (true);


-- Create the group_events table
CREATE TABLE group_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_id BIGINT NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
  location_id BIGINT REFERENCES group_event_locations(id) ON DELETE SET NULL,
  name TEXT NOT NULL,
  date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME,
  description TEXT,
  is_recurring BOOLEAN NOT NULL DEFAULT false,
  recurrence_pattern TEXT CHECK (recurrence_pattern IN ('weekly', 'bi-weekly', 'monthly', 'annually')),
  recurrence_end_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT recurrence_end_after_start CHECK (
    recurrence_end_date IS NULL OR recurrence_end_date > date
  )
);

CREATE INDEX idx_group_events_website_id ON group_events (website_id);
CREATE INDEX idx_group_events_date ON group_events (date);

ALTER TABLE group_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow authenticated users to read group_events"
  ON group_events FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Allow authenticated users to insert group_events"
  ON group_events FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Allow authenticated users to update group_events"
  ON group_events FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow authenticated users to delete group_events"
  ON group_events FOR DELETE
  TO authenticated
  USING (true);

-- Auto-update updated_at on row changes
CREATE OR REPLACE FUNCTION update_group_events_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER group_events_updated_at
  BEFORE UPDATE ON group_events
  FOR EACH ROW
  EXECUTE FUNCTION update_group_events_updated_at();
