-- Create the visibility-brigade-submissions table
CREATE TABLE "visibility-brigade-submissions" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_id BIGINT NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
  form_data JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_vb_submissions_website_id ON "visibility-brigade-submissions" (website_id);

ALTER TABLE "visibility-brigade-submissions" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public insert on visibility-brigade-submissions"
  ON "visibility-brigade-submissions" FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

CREATE POLICY "Allow authenticated users to read visibility-brigade-submissions"
  ON "visibility-brigade-submissions" FOR SELECT
  TO authenticated
  USING (true);
