-- Create the visibility-brigade-forms table
CREATE TABLE "visibility-brigade-forms" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_id BIGINT NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
  label TEXT NOT NULL,
  field_type TEXT NOT NULL DEFAULT 'text',
  placeholder TEXT,
  options JSONB,
  default_value TEXT,
  required BOOLEAN NOT NULL DEFAULT false,
  visible BOOLEAN NOT NULL DEFAULT true,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Create index on website_id for faster lookups
CREATE INDEX idx_vb_forms_website_id ON "visibility-brigade-forms" (website_id);

-- Enable Row Level Security
ALTER TABLE "visibility-brigade-forms" ENABLE ROW LEVEL SECURITY;

-- RLS policies (adjust as needed for your auth setup)
CREATE POLICY "Allow authenticated users to read visibility-brigade-forms"
  ON "visibility-brigade-forms" FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Allow authenticated users to insert visibility-brigade-forms"
  ON "visibility-brigade-forms" FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Allow authenticated users to update visibility-brigade-forms"
  ON "visibility-brigade-forms" FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow authenticated users to delete visibility-brigade-forms"
  ON "visibility-brigade-forms" FOR DELETE
  TO authenticated
  USING (true);
